name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x", "7.0.x"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{matrix.dotnet-version}}-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-${{matrix.dotnet-version}}-${{ hashFiles('**/*.csproj') }}
            ${{ runner.os }}-nuget-${{matrix.dotnet-version}}-
            ${{ runner.os }}-nuget-
      - name: Install dependencies
        run: dotnet restore
      - name: Check format
        run: dotnet format --verify-no-changes
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --collect:"XPlat Code Coverage"
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: BatchSharp.Tests/TestResults/*/coverage.cobertura.xml

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          flags: unittests
